// Code generated by tui generate. DO NOT EDIT.
// Source: app.gsx

package tui

import (
	"context"
	"time"

	"github.com/efuturetoday/nocturn/internal/chat"
	"github.com/efuturetoday/nocturn/internal/tui/logring"
	"github.com/efuturetoday/nocturn/internal/tui/transcript"
	"github.com/efuturetoday/nocturn/internal/workspace"
	tui "github.com/grindlemire/go-tui"
)

type app struct {
	// app is the running framework App, assigned by the generated BindApp. Declaring the field is
	// the documented way to get hold of it; nothing here constructs it.
	app *tui.App

	// ctx is the process context, held because firing an agent needs one and the framework's
	// callbacks carry none.
	ctx context.Context
	// ws is nil until the opener finishes. Every path that reaches it goes through ready(), so the
	// UI is usable — and honest about what it cannot do yet — from the first frame.
	ws       *workspace.Workspace
	loaded   <-chan opened
	feed     *Feed
	approver *Approver
	ring     *logring.Ring
	model    string
	// turnStart is when the running turn began, for the context bar's clock. A plain field, not a
	// State: the second-tick that already redraws a running turn is what puts the new number on
	// screen, so nothing that writes it needs to mark a frame dirty.
	turnStart time.Time

	activeID   *tui.State[string]
	activeKind *tui.State[string]
	view       *tui.State[transcript.View]
	chats      *tui.State[[]chat.Meta]
	runs       *tui.State[[]chat.Meta]
	cursor     *tui.State[int]
	draft      *tui.State[string]
	// flash is what just happened, with a deadline on it. Where you are, what is running and what it
	// cost are NOT here — those are derived in contextBar, because they are facts about the state
	// rather than events, and sharing one slot is what made the old status line unreadable.
	flash       *tui.State[flashMsg]
	logOpen     *tui.State[bool]
	inspectOpen *tui.State[bool]
	// filter picks which conversations the sidebar shows. All of them, by default.
	filter *tui.State[listFilter]
	// The workspace view: which page is up, what has been typed into its filter, and whether the
	// keyboard is currently going into that filter.
	inspectSection *tui.State[sectionID]
	inspectFilter  *tui.State[string]
	inspectTyping  *tui.State[bool]
	// The knowledge base by top-level directory, and the file count it was built from. Plain fields
	// and not states: they are rebuilt only when the count changes, because the paths are a disk
	// walk — see refreshInspect.
	docDirs  []boardLine
	docFiles int
	logs     *tui.State[[]logring.Line]
	tokens   *tui.State[int]
	ask      *tui.State[*Ask]
	asking   *tui.State[bool]
	// askCursor is which option the arrow keys have walked to. The digits stay the fastest way to
	// answer; this is the same gesture the list and the palette use, so the question does not have
	// to be read twice to work out how to answer it.
	askCursor *tui.State[int]
	// The palette: whether it is up, what has been typed into it, and which entry is picked. The
	// query is a plain string and not an <input> on purpose — see paletteKeys.
	paletteOpen *tui.State[bool]
	// paletteStep is which of the palette's two questions is up: the verb, or the thing it acts on.
	paletteStep   *tui.State[paletteStep]
	paletteQuery  *tui.State[string]
	paletteCursor *tui.State[int]
	// paletteArmed is the conversation a delete has been chosen for and not yet confirmed. It is a
	// state rather than a flag because the confirmation has to name what it will destroy.
	paletteArmed *tui.State[string]
	// The tool overlay: whether it is up and the call it is showing, copied at the moment it opened.
	toolOpen *tui.State[bool]
	tool     *tui.State[transcript.Tool]
	// toolRefs is where each call's line landed on screen, keyed by turn and call — the only way to
	// tell which one a click hit, since the blocks above it are variable height. go-tui offers no
	// other mechanism: even its own HandleClicks helper is a ref and a ContainsPoint (click.go).
	toolRefs *tui.RefMap[uint64]
	// The overlays' scroll positions live on the ROOT rather than inside their panes, because the
	// root is what handles their wheel — see HandleMouse.
	toolScroll    *tui.State[int]
	inspectScroll *tui.State[int]

	// The panes bind their own elements to these; the root holds them only so it can move the
	// keyboard onto a pane (focusOn) and read the transcript's width.
	side        *tui.Ref
	body        *tui.Ref
	logView     *tui.Ref
	inspectView *tui.Ref
	toolView    *tui.Ref
	composer    *tui.Ref
	// wantFocus is the pane the keyboard is owed, settled after the next frame. See focusOn.
	wantFocus *tui.Ref
}

type opened struct {
	ws  *workspace.Workspace
	err error
}

func newApp(ctx context.Context, d Deps, loaded <-chan opened) *app {
	return &app{
		ctx:      ctx,
		loaded:   loaded,
		feed:     d.Feed,
		approver: d.Approver,
		ring:     d.Ring,
		model:    d.Model,

		activeID:       tui.NewState(""),
		activeKind:     tui.NewState("user"),
		view:           tui.NewState(transcript.View{}),
		chats:          tui.NewState([]chat.Meta{}),
		runs:           tui.NewState([]chat.Meta{}),
		cursor:         tui.NewState(-1),
		draft:          tui.NewState(""),
		flash:          tui.NewState(flashMsg{}),
		logOpen:        tui.NewState(false),
		inspectOpen:    tui.NewState(false),
		filter:         tui.NewState(filterChats),
		inspectSection: tui.NewState(sectionBoard),
		inspectFilter:  tui.NewState(""),
		inspectTyping:  tui.NewState(false),
		logs:           tui.NewState([]logring.Line{}),
		tokens:         tui.NewState(0),
		ask:            tui.NewState[*Ask](nil),
		asking:         tui.NewState(false),
		askCursor:      tui.NewState(0),
		paletteOpen:    tui.NewState(false),
		paletteStep:    tui.NewState(stepRoot),
		paletteQuery:   tui.NewState(""),
		paletteCursor:  tui.NewState(0),
		paletteArmed:   tui.NewState(""),
		toolOpen:       tui.NewState(false),
		tool:           tui.NewState(transcript.Tool{}),
		toolRefs:       tui.NewRefMap[uint64](),
		toolScroll:     tui.NewState(0),
		inspectScroll:  tui.NewState(0),

		side:        tui.NewRef(),
		body:        tui.NewRef(),
		logView:     tui.NewRef(),
		inspectView: tui.NewRef(),
		toolView:    tui.NewRef(),
		composer:    tui.NewRef(),
	}
}

func (a *app) Render(app *tui.App) *tui.Element {
	now := time.Now()
	at := a.region()
	probs := a.problems()
	page := a.page(a.inspectSection.Get())
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexGrow(1),
		tui.WithMinHeight(0),
	)
	__tui_2 := app.Mount(a, 0, func() tui.Component {
		return Sidebar(List{Box: a.side, Focus: a.focusOn, Cursor: a.cursor, ActiveID: a.activeID,
			Filter: a.filter, Rows: a.rows, Sizes: a.listSizes, OnSelect: a.selectRow,
			Focused: at == regList})
	})
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithMinHeight(0),
	)
	__tui_4_children := []*tui.Element{}
	for i, b := range a.view.Get().Blocks {
		_ = i
		__tui_5 := app.Mount(a, tui.MountKey(2, a.activeID.Get(), i), func() tui.Component {
			return BlockView(b, i, now, a.bodyWidth(), a.toolRefs)
		})
		__tui_4_children = append(__tui_4_children, __tui_5)
	}
	__tui_4 := app.Mount(a, tui.MountKey(1, a.activeID.Get()), func() tui.Component {
		return ScrollPane(Pane{
			Box: a.body, Focus: a.focusOn, Follow: true,
			Title:   paneTitle(a.bodyTitle(), at == regTranscript),
			Focused: at == regTranscript,
		}, __tui_4_children)
	})
	__tui_3.AddChild(__tui_4)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	if a.logOpen.Get() {
		__tui_6_children := []*tui.Element{}
		for __idx_0, l := range a.logs.Get() {
			_ = __idx_0
			__tui_7 := app.Mount(a, tui.MountKey(4, __idx_0), func() tui.Component {
				return LogLine(l)
			})
			__tui_6_children = append(__tui_6_children, __tui_7)
		}
		__tui_6 := app.Mount(a, 3, func() tui.Component {
			return ScrollPane(Pane{
				Box: a.logView, Focus: a.focusOn, Height: 12, Follow: true,
				Title:   paneTitle(" logs ", at == regLogs),
				Focused: at == regLogs,
			}, __tui_6_children)
		})
		__tui_0.AddChild(__tui_6)
	}
	if a.readOnly() {
		__tui_8 := app.Mount(a, 5, func() tui.Component {
			return ReadOnlyBar()
		})
		__tui_0.AddChild(__tui_8)
	} else {
		__tui_9 := app.MountPersistent(a, 6, func() tui.Component {
			return tui.NewInput(
				tui.WithInputValue(a.draft),
				tui.WithInputOnSubmit(a.submit),
				tui.WithInputAutoFocus(true),
				tui.WithInputWidth(a.width()),
				tui.WithInputPlaceholder("message, or /help"),
				tui.WithInputBorder(tui.BorderSingle),
				tui.WithInputFocusColor(accent),
			)
		})
		a.composer.Set(__tui_9)
		__tui_0.AddChild(__tui_9)
	}
	__tui_10 := app.Mount(a, 7, func() tui.Component {
		return ContextBar(a.where(), a.activity(), a.tokens.Get(), a.model, a.width())
	})
	__tui_0.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithText(a.hintLine()),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_11)
	__tui_12 := app.MountPersistent(a, 8, func() tui.Component {
		return tui.NewModal(
			tui.WithModalOpen(a.asking),
			tui.WithModalCloseOnEscape(false),
			tui.WithModalCloseOnBackdropClick(false),
			tui.WithModalBackdrop("dim"),
			tui.WithModalElementOptions(tui.WithJustify(tui.JustifyCenter), tui.WithAlign(tui.AlignCenter)),
		)
	})
	__tui_13 := app.Mount(a, 9, func() tui.Component {
		return Approval(a.ask.Get(), a.askCursor.Get())
	})
	__tui_12.AddChild(__tui_13)
	__tui_0.AddChild(__tui_12)
	__tui_14 := app.MountPersistent(a, 10, func() tui.Component {
		return tui.NewModal(
			tui.WithModalOpen(a.paletteOpen),
			tui.WithModalCloseOnEscape(false),
			tui.WithModalCloseOnBackdropClick(false),
			tui.WithModalBackdrop("dim"),
			tui.WithModalElementOptions(tui.WithJustify(tui.JustifyCenter), tui.WithAlign(tui.AlignCenter)),
		)
	})
	__tui_15 := app.Mount(a, 11, func() tui.Component {
		return Palette(a.paletteStep.Get().title(), a.paletteQuery.Get(), a.paletteEntries(), a.paletteCursor.Get())
	})
	__tui_14.AddChild(__tui_15)
	__tui_0.AddChild(__tui_14)
	__tui_16 := app.MountPersistent(a, 12, func() tui.Component {
		return tui.NewModal(
			tui.WithModalOpen(a.toolOpen),
			tui.WithModalCloseOnEscape(false),
			tui.WithModalCloseOnBackdropClick(false),
			tui.WithModalBackdrop("dim"),
			tui.WithModalElementOptions(tui.WithJustify(tui.JustifyCenter), tui.WithAlign(tui.AlignCenter)),
		)
	})
	__tui_17 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidth(toolDetailWidth),
	)
	__tui_18_children := []*tui.Element{}
	__tui_19 := app.Mount(a, 14, func() tui.Component {
		return ToolDetail(a.tool.Get())
	})
	__tui_18_children = append(__tui_18_children, __tui_19)
	__tui_18 := app.Mount(a, 13, func() tui.Component {
		return ScrollPane(Pane{
			Box: a.toolView, Focus: a.focusOn, Title: a.toolTitle(),
			Height: toolDetailHeight, Focused: true, Offset: a.toolScroll,
		}, __tui_18_children)
	})
	__tui_17.AddChild(__tui_18)
	__tui_16.AddChild(__tui_17)
	__tui_0.AddChild(__tui_16)
	__tui_20 := app.MountPersistent(a, 15, func() tui.Component {
		return tui.NewModal(
			tui.WithModalOpen(a.inspectOpen),
			tui.WithModalCloseOnEscape(false),
			tui.WithModalCloseOnBackdropClick(false),
			tui.WithModalBackdrop("dim"),
			tui.WithModalElementOptions(tui.WithPadding(1)),
		)
	})
	__tui_21_children := []*tui.Element{}
	if a.inspectSection.Get() == sectionBoard {
		__tui_22 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifySpaceBetween),
			tui.WithFlexShrink(0),
			tui.WithWidth(a.inspectWidth()),
		)
		__tui_23 := tui.New(
			tui.WithText(a.workspaceName()),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_22.AddChild(__tui_23)
		__tui_24 := tui.New(
			tui.WithText(a.capabilitySummary()),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_22.AddChild(__tui_24)
		__tui_21_children = append(__tui_21_children, __tui_22)
		__tui_25 := tui.New(
			tui.WithHeight(1),
		)
		__tui_21_children = append(__tui_21_children, __tui_25)
		if len(probs) > 0 {
			__tui_26 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
				tui.WithFlexShrink(0),
				tui.WithBorder(tui.BorderThick),
				tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Red)),
				tui.WithPaddingTRBL(0, 1, 0, 1),
				tui.WithBorderTitle(problemSummary(probs)),
			)
			for __idx_0, p := range probs {
				_ = __idx_0
				__tui_27 := app.Mount(a, tui.MountKey(17, __idx_0), func() tui.Component {
					return ProblemBlock(p, a.inspectWidth()-4)
				})
				__tui_26.AddChild(__tui_27)
			}
			__tui_21_children = append(__tui_21_children, __tui_26)
		} else {
			__tui_28 := tui.New(
				tui.WithText("⏺ all clear — every server up, the vault open"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
			)
			__tui_21_children = append(__tui_21_children, __tui_28)
		}
		__tui_29 := tui.New(
			tui.WithHeight(1),
		)
		__tui_21_children = append(__tui_21_children, __tui_29)
		for __idx_0, row := range a.boardRows() {
			_ = __idx_0
			__tui_30 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				tui.WithFlexShrink(0),
				tui.WithGap(2),
			)
			for __idx_1, s := range row {
				_ = __idx_1
				__tui_31 := app.Mount(a, tui.MountKey(18, __idx_0, __idx_1), func() tui.Component {
					return BoardSection(s, a.boardColWidth(), a.boardNameWidth())
				})
				__tui_30.AddChild(__tui_31)
			}
			__tui_21_children = append(__tui_21_children, __tui_30)
			__tui_32 := tui.New(
				tui.WithHeight(1),
			)
			__tui_21_children = append(__tui_21_children, __tui_32)
		}
	} else {
		__tui_33 := tui.New(
			tui.WithText(page.Summary),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_21_children = append(__tui_21_children, __tui_33)
		if a.inspectSection.Get().Filterable() {
			__tui_34 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				tui.WithGap(1),
				tui.WithFlexShrink(0),
			)
			__tui_35 := tui.New(
				tui.WithText("/"),
				tui.WithTextStyle(cursorStyle()),
			)
			__tui_34.AddChild(__tui_35)
			__tui_36 := tui.New(
				tui.WithText(a.inspectFilter.Get()),
			)
			__tui_34.AddChild(__tui_36)
			if a.inspectTyping.Get() {
				__tui_37 := tui.New(
					tui.WithText("▌"),
					tui.WithTextStyle(cursorStyle()),
				)
				__tui_34.AddChild(__tui_37)
			}
			__tui_21_children = append(__tui_21_children, __tui_34)
		}
		__tui_38 := tui.New(
			tui.WithHR(),
		)
		__tui_21_children = append(__tui_21_children, __tui_38)
		for __idx_0, b := range page.Blocks {
			_ = __idx_0
			__tui_39 := app.Mount(a, tui.MountKey(19, __idx_0), func() tui.Component {
				return PageBlock(b, a.inspectWidth())
			})
			__tui_21_children = append(__tui_21_children, __tui_39)
		}
		for __idx_0, row := range pageGridRows(page) {
			_ = __idx_0
			__tui_40 := app.Mount(a, tui.MountKey(20, __idx_0), func() tui.Component {
				return GridRow(row, a.pageCellWidth(page))
			})
			__tui_21_children = append(__tui_21_children, __tui_40)
		}
	}
	__tui_21 := app.Mount(a, 16, func() tui.Component {
		return ScrollPane(Pane{
			Box: a.inspectView, Focus: a.focusOn, Title: a.inspectTitle(),
			Focused: true, Offset: a.inspectScroll,
		}, __tui_21_children)
	})
	__tui_20.AddChild(__tui_21)
	__tui_0.AddChild(__tui_20)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (a *app) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*app)
	if !ok {
		return
	}
	a.app = f.app
	a.ctx = f.ctx
	a.ws = f.ws
	a.feed = f.feed
	a.approver = f.approver
	a.ring = f.ring
	a.model = f.model
	a.turnStart = f.turnStart
	a.docDirs = f.docDirs
	a.docFiles = f.docFiles
}

func (a *app) UpdateProps(fresh tui.Component) {
	a.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*app)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (a *app) bindAppFields(app *tui.App) {
	a.app = app
	if a.activeID != nil {
		a.activeID.BindApp(app)
	}
	if a.activeKind != nil {
		a.activeKind.BindApp(app)
	}
	if a.view != nil {
		a.view.BindApp(app)
	}
	if a.chats != nil {
		a.chats.BindApp(app)
	}
	if a.runs != nil {
		a.runs.BindApp(app)
	}
	if a.cursor != nil {
		a.cursor.BindApp(app)
	}
	if a.draft != nil {
		a.draft.BindApp(app)
	}
	if a.flash != nil {
		a.flash.BindApp(app)
	}
	if a.logOpen != nil {
		a.logOpen.BindApp(app)
	}
	if a.inspectOpen != nil {
		a.inspectOpen.BindApp(app)
	}
	if a.filter != nil {
		a.filter.BindApp(app)
	}
	if a.inspectSection != nil {
		a.inspectSection.BindApp(app)
	}
	if a.inspectFilter != nil {
		a.inspectFilter.BindApp(app)
	}
	if a.inspectTyping != nil {
		a.inspectTyping.BindApp(app)
	}
	if a.logs != nil {
		a.logs.BindApp(app)
	}
	if a.tokens != nil {
		a.tokens.BindApp(app)
	}
	if a.ask != nil {
		a.ask.BindApp(app)
	}
	if a.asking != nil {
		a.asking.BindApp(app)
	}
	if a.askCursor != nil {
		a.askCursor.BindApp(app)
	}
	if a.paletteOpen != nil {
		a.paletteOpen.BindApp(app)
	}
	if a.paletteStep != nil {
		a.paletteStep.BindApp(app)
	}
	if a.paletteQuery != nil {
		a.paletteQuery.BindApp(app)
	}
	if a.paletteCursor != nil {
		a.paletteCursor.BindApp(app)
	}
	if a.paletteArmed != nil {
		a.paletteArmed.BindApp(app)
	}
	if a.toolOpen != nil {
		a.toolOpen.BindApp(app)
	}
	if a.tool != nil {
		a.tool.BindApp(app)
	}
	if a.toolScroll != nil {
		a.toolScroll.BindApp(app)
	}
	if a.inspectScroll != nil {
		a.inspectScroll.BindApp(app)
	}
}

func (a *app) BindApp(app *tui.App) {
	a.bindAppFields(app)
}

var _ tui.AppBinder = (*app)(nil)
