// Code generated by tui generate. DO NOT EDIT.
// Source: blocks.gsx

package tui

import (
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/efuturetoday/nocturn/internal/tui/logring"
	"github.com/efuturetoday/nocturn/internal/tui/transcript"
	tui "github.com/grindlemire/go-tui"
)

type blockView struct {
	block transcript.Block
	now   time.Time
	width int
	// at is this block's index in the transcript. It is half the key a call's line is remembered by
	// — see toolKey.
	at int
	// toolRefs is where each call's line landed on screen. It is the ROOT's map, because the refs
	// have to outlive this block: a block is rebuilt on every frame and a click arrives between two
	// of them.
	toolRefs *tui.RefMap[uint64]
}

var _ = func() tui.Viewable { return ToolLine(transcript.Tool{}, time.Time{}, 80) }

func indentCells(depth int) int {
	return min(depth, 6) * 2
}

func toolTiming(t transcript.Tool, now time.Time) string {
	if !t.Running {
		return t.Duration.Round(time.Millisecond).String()
	}
	if t.Started.IsZero() {
		return "…"
	}
	return now.Sub(t.Started).Round(time.Second).String()
}

func oneLine(s string, width int) string {
	s = strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
	if width <= 0 {
		return s
	}
	r := []rune(s)
	if len(r) <= width {
		return s
	}
	return string(r[:width-1]) + "…"
}

func toolBudget(t transcript.Tool, width int) (args, result int) {
	const timing, gaps, icon = 8, 5, 2
	free := width - indentCells(t.Depth) - icon - len([]rune(t.Name)) - timing - gaps
	if free < 24 {
		return 12, 12
	}

	out := t.Result
	if t.Err != "" {
		out = t.Err
	}
	// The collapsed length, because that is what is drawn: oneLine folds newlines away first, and a
	// value measured before folding would reserve room for characters that never appear.
	a, r := len([]rune(oneLine(t.Args, 0))), len([]rune(oneLine(out, 0)))

	switch {
	case a+r <= free:
		return a, r // both whole, and room to spare
	case r <= free/2:
		return free - r, r // the output fits; everything else goes to the input
	case a <= free/2:
		return a, free - a // the input fits; everything else goes to the output
	case t.Err != "":
		args = free / 3
	default:
		args = free * 2 / 3
	}
	return args, free - args
}

func toolArgsWidth(t transcript.Tool, width int) int { a, _ := toolBudget(t, width); return a }

func toolResultWidth(t transcript.Tool, width int) int { _, r := toolBudget(t, width); return r }

func BlockView(b transcript.Block, at int, now time.Time, width int, toolRefs *tui.RefMap[uint64]) *blockView {
	return &blockView{block: b, at: at, now: now, width: width, toolRefs: toolRefs}
}

func chipLabel(name string, n int, width int) string {
	r := []rune(fmt.Sprintf("%s %d", name, n))
	if len(r) >= width {
		return string(r[:width])
	}
	pad := width - len(r)
	return strings.Repeat(" ", pad/2) + string(r) + strings.Repeat(" ", pad-pad/2)
}

func chipStyle(active bool) tui.Style {
	if active {
		return tui.NewStyle().Background(accent).Foreground(onAccent).Bold()
	}
	return tui.NewStyle().Foreground(tui.BrightBlack)
}

func activityStyle(activity string) tui.Style {
	if strings.HasPrefix(activity, "⏵") {
		return tui.NewStyle().Foreground(tui.Yellow)
	}
	return tui.NewStyle().Dim()
}

func wrap(s string, width int) []string {
	s = strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
	if s == "" || width <= 0 {
		return nil
	}
	var out []string
	line := make([]rune, 0, width)
	flush := func() {
		if len(line) > 0 {
			out = append(out, string(line))
			line = line[:0]
		}
	}
	for _, word := range strings.Fields(s) {
		w := []rune(word)
		// A word wider than the line is cut across lines rather than left to overflow — a URL with no
		// spaces in it would otherwise push the whole box sideways.
		for len(w) > width {
			flush()
			out = append(out, string(w[:width]))
			w = w[width:]
		}
		switch {
		case len(line) == 0:
			line = append(line, w...)
		case len(line)+1+len(w) <= width:
			line = append(line, ' ')
			line = append(line, w...)
		default:
			flush()
			line = append(line, w...)
		}
	}
	flush()
	return out
}

func toneStyle(t tone) tui.Style {
	switch t {
	case toneBad:
		return tui.NewStyle().Foreground(tui.Red)
	case toneWarn:
		return tui.NewStyle().Foreground(tui.Yellow)
	case toneGood:
		return tui.NewStyle().Foreground(tui.Green)
	case toneDim:
		return tui.NewStyle().Dim()
	default:
		return tui.NewStyle()
	}
}

func sectionTitleStyle() tui.Style { return tui.NewStyle().Foreground(accentHigh).Bold() }

func problemTone(p problem) tone {
	if p.Bad {
		return toneBad
	}
	return toneWarn
}

func cursorStyle() tui.Style {
	return tui.NewStyle().Foreground(accentHigh).Bold()
}

func rowStyle(selected, unread bool) tui.Style {
	s := tui.NewStyle()
	if selected {
		s = s.Foreground(accentHigh)
	}
	if unread {
		s = s.Bold()
	}
	return s
}

func levelStyle(l slog.Level) tui.Style {
	switch {
	case l >= slog.LevelError:
		return tui.NewStyle().Foreground(tui.Red)
	case l >= slog.LevelWarn:
		return tui.NewStyle().Foreground(tui.Yellow)
	case l >= slog.LevelInfo:
		return tui.NewStyle().Foreground(tui.BrightWhite)
	default:
		return tui.NewStyle().Dim()
	}
}

func lastRunes(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[len(r)-n:])
}

type ToolLineView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ToolLineView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ToolLineView) GetRoot() *tui.Element { return v.Root }

func (v *ToolLineView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ToolLineView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ToolLineView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ToolLineView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ToolLineView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ToolLineView)(nil)

var _ tui.AppUnbinder = (*ToolLineView)(nil)

var _ tui.PropsUpdater = (*ToolLineView)(nil)

func ToolLine(t transcript.Tool, now time.Time, width int) *ToolLineView {
	var view ToolLineView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(indentCells(t.Depth)),
	)
	__tui_0.AddChild(__tui_1)
	if t.Err != "" {
		__tui_2 := tui.New(
			tui.WithText("✗ "+t.Name),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		__tui_0.AddChild(__tui_2)
	} else if t.Running {
		__tui_3 := tui.New(
			tui.WithText("◐ "+t.Name),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_3)
	} else {
		__tui_4 := tui.New(
			tui.WithText("⏺ "+t.Name),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
		)
		__tui_0.AddChild(__tui_4)
	}
	__tui_5 := tui.New(
		tui.WithText(oneLine(t.Args, toolArgsWidth(t, width))),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText(toolTiming(t, now)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_6)
	if t.Err != "" {
		__tui_7 := tui.New(
			tui.WithText(oneLine(t.Err, toolResultWidth(t, width))),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		__tui_0.AddChild(__tui_7)
	} else if !t.Running && t.Result != "" {
		__tui_8 := tui.New(
			tui.WithText("→ "+oneLine(t.Result, toolResultWidth(t, width))),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_8)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ToolLineView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ToolTailView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ToolTailView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ToolTailView) GetRoot() *tui.Element { return v.Root }

func (v *ToolTailView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ToolTailView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ToolTailView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ToolTailView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ToolTailView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ToolTailView)(nil)

var _ tui.AppUnbinder = (*ToolTailView)(nil)

var _ tui.PropsUpdater = (*ToolTailView)(nil)

func ToolTail(t transcript.Tool) *ToolTailView {
	var view ToolTailView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexShrink(0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(indentCells(t.Depth + 1)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(oneLine(lastRunes(t.Stream, 200), 0)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ToolTailView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type UserBlockView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *UserBlockView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *UserBlockView) GetRoot() *tui.Element { return v.Root }

func (v *UserBlockView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *UserBlockView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *UserBlockView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *UserBlockView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*UserBlockView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*UserBlockView)(nil)

var _ tui.AppUnbinder = (*UserBlockView)(nil)

var _ tui.PropsUpdater = (*UserBlockView)(nil)

func UserBlock(b transcript.Block) *UserBlockView {
	var view UserBlockView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithText("you ›"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(b.Text),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = UserBlockView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type NoticeBlockView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *NoticeBlockView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *NoticeBlockView) GetRoot() *tui.Element { return v.Root }

func (v *NoticeBlockView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *NoticeBlockView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *NoticeBlockView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *NoticeBlockView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*NoticeBlockView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*NoticeBlockView)(nil)

var _ tui.AppUnbinder = (*NoticeBlockView)(nil)

var _ tui.PropsUpdater = (*NoticeBlockView)(nil)

func NoticeBlock(b transcript.Block) *NoticeBlockView {
	var view NoticeBlockView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_1 := tui.New(
		tui.WithText("◆"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(b.Text),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = NoticeBlockView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

func (v *blockView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexShrink(0),
	)
	if v.block.Role == transcript.User {
		__tui_1 := UserBlock(v.block)
		__tui_0.AddChild(__tui_1.Root)
	} else if v.block.Role == transcript.Notice {
		__tui_2 := NoticeBlock(v.block)
		__tui_0.AddChild(__tui_2.Root)
	} else {
		for __idx_0, t := range v.block.Tools {
			_ = __idx_0
			__tui_3 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
				tui.WithFlexShrink(0),
			)
			v.toolRefs.Put(toolKey(v.at, t.ID), __tui_3)
			__tui_4 := ToolLine(t, v.now, v.width)
			__tui_3.AddChild(__tui_4.Root)
			if t.Running && t.Stream != "" {
				__tui_5 := ToolTail(t)
				__tui_3.AddChild(__tui_5.Root)
			}
			__tui_0.AddChild(__tui_3)
		}
		if v.block.Pending && v.block.Think != "" {
			__tui_6 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				tui.WithGap(1),
			)
			__tui_7 := tui.New(
				tui.WithText("⋮"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_6.AddChild(__tui_7)
			__tui_8 := tui.New(
				tui.WithText(oneLine(lastRunes(v.block.Think, 160), 0)),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_6.AddChild(__tui_8)
			__tui_0.AddChild(__tui_6)
		}
		if v.block.Text != "" && v.block.Pending {
			__tui_9 := tui.New(
				tui.WithText(v.block.Text),
			)
			__tui_0.AddChild(__tui_9)
		} else if v.block.Text != "" {
			__tui_10 := app.MountPersistent(v, 0, func() tui.Component {
				return tui.NewMarkdown(
					tui.WithMarkdownSource(v.block.Text),
					tui.WithMarkdownWidth(v.width),
				)
			})
			__tui_0.AddChild(__tui_10)
		}
		if v.block.Pending && v.block.Text == "" {
			__tui_11 := tui.New(
				tui.WithText("…"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_0.AddChild(__tui_11)
		}
		if v.block.Cancelled {
			__tui_12 := tui.New(
				tui.WithText("[cancelled]"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_0.AddChild(__tui_12)
		} else if v.block.Err != "" {
			__tui_13 := tui.New(
				tui.WithText("[stopped: "+strings.ReplaceAll(v.block.Err, "\n", " ")+"]"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
			)
			__tui_0.AddChild(__tui_13)
		}
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (v *blockView) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*blockView)
	if !ok {
		return
	}
	v.block = f.block
	v.now = f.now
	v.width = f.width
	v.at = f.at
}

func (v *blockView) UpdateProps(fresh tui.Component) {
	v.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*blockView)(nil)

type SidebarRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SidebarRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SidebarRowView) GetRoot() *tui.Element { return v.Root }

func (v *SidebarRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SidebarRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SidebarRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SidebarRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SidebarRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SidebarRowView)(nil)

var _ tui.AppUnbinder = (*SidebarRowView)(nil)

var _ tui.PropsUpdater = (*SidebarRowView)(nil)

func SidebarRow(r row, selected bool, active bool) *SidebarRowView {
	var view SidebarRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexShrink(0),
	)
	if r.Kind == rowEmpty {
		__tui_1 := tui.New(
			tui.WithText("  "+r.Label),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_1)
	} else {
		__tui_2 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		)
		__tui_3 := tui.New(
			tui.WithWidth(gutter),
		)
		__tui_2.AddChild(__tui_3)
		if selected {
			__tui_4 := tui.New(
				tui.WithText("▸"),
				tui.WithTextStyle(cursorStyle()),
			)
			__tui_2.AddChild(__tui_4)
		} else if active {
			__tui_5 := tui.New(
				tui.WithText("│"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
			)
			__tui_2.AddChild(__tui_5)
		} else {
			__tui_6 := tui.New(
				tui.WithWidth(1),
			)
			__tui_2.AddChild(__tui_6)
		}
		__tui_7 := tui.New(
			tui.WithWidth(1),
		)
		__tui_2.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText(oneLine(r.Label, labelWidth)),
			tui.WithTextStyle(rowStyle(selected, r.Unread)),
		)
		__tui_2.AddChild(__tui_8)
		__tui_0.AddChild(__tui_2)
		__tui_9 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		)
		__tui_10 := tui.New(
			tui.WithWidth(gutter + 2),
		)
		__tui_9.AddChild(__tui_10)
		if r.Kind == rowRun {
			__tui_11 := tui.New(
				tui.WithText(oneLine(r.Source, labelWidth-8)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
			)
			__tui_9.AddChild(__tui_11)
		} else {
			__tui_12 := tui.New(
				tui.WithText("you"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_9.AddChild(__tui_12)
		}
		__tui_13 := tui.New(
			tui.WithWidth(1),
		)
		__tui_9.AddChild(__tui_13)
		__tui_14 := tui.New(
			tui.WithText("· "+r.When),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_9.AddChild(__tui_14)
		if r.Unread {
			__tui_15 := tui.New(
				tui.WithWidth(1),
			)
			__tui_9.AddChild(__tui_15)
			__tui_16 := tui.New(
				tui.WithText("•"),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
			)
			__tui_9.AddChild(__tui_16)
		}
		__tui_0.AddChild(__tui_9)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SidebarRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ContextBarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ContextBarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ContextBarView) GetRoot() *tui.Element { return v.Root }

func (v *ContextBarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ContextBarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ContextBarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ContextBarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ContextBarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ContextBarView)(nil)

var _ tui.AppUnbinder = (*ContextBarView)(nil)

var _ tui.PropsUpdater = (*ContextBarView)(nil)

func ContextBar(where string, activity string, tokens int, model string, width int) *ContextBarView {
	var view ContextBarView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithWidth(width),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_2 := tui.New(
		tui.WithText(where),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("·"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(activity),
		tui.WithTextStyle(activityStyle(activity)),
	)
	__tui_1.AddChild(__tui_4)
	if tokens > 0 {
		__tui_5 := tui.New(
			tui.WithText("·"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText(fmt.Sprintf("%d tok", tokens)),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_6)
	}
	__tui_0.AddChild(__tui_1)
	__tui_7 := tui.New(
		tui.WithText(model),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_7)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ContextBarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ReadOnlyBarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ReadOnlyBarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ReadOnlyBarView) GetRoot() *tui.Element { return v.Root }

func (v *ReadOnlyBarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ReadOnlyBarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ReadOnlyBarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ReadOnlyBarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ReadOnlyBarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ReadOnlyBarView)(nil)

var _ tui.AppUnbinder = (*ReadOnlyBarView)(nil)

var _ tui.PropsUpdater = (*ReadOnlyBarView)(nil)

func ReadOnlyBar() *ReadOnlyBarView {
	var view ReadOnlyBarView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_1 := tui.New(
		tui.WithText("⌾"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("agent run — read only. Ctrl+N starts a chat."),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ReadOnlyBarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type PaletteView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *PaletteView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *PaletteView) GetRoot() *tui.Element { return v.Root }

func (v *PaletteView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *PaletteView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *PaletteView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *PaletteView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*PaletteView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*PaletteView)(nil)

var _ tui.AppUnbinder = (*PaletteView)(nil)

var _ tui.PropsUpdater = (*PaletteView)(nil)

func Palette(title string, query string, entries []paletteEntry, cursor int) *PaletteView {
	var view PaletteView
	var watchers []tui.Watcher

	var __tui_7_views []*PaletteRowView
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithWidth(paletteWidth),
		tui.WithBorderTitle(title),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_2 := tui.New(
		tui.WithText("›"),
		tui.WithTextStyle(cursorStyle()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(query),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("▌"),
		tui.WithTextStyle(cursorStyle()),
	)
	__tui_1.AddChild(__tui_4)
	__tui_0.AddChild(__tui_1)
	__tui_5 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_5)
	if len(entries) == 0 {
		__tui_6 := tui.New(
			tui.WithText("nothing matches"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_6)
	}
	for i, e := range entries {
		_ = i
		__tui_7 := PaletteRow(e, i == cursor)
		__tui_0.AddChild(__tui_7.Root)
		__tui_7_views = append(__tui_7_views, __tui_7)
	}

	for _, __cv := range __tui_7_views {
		watchers = append(watchers, __cv.GetWatchers()...)
	}

	__bindApp := func(app *tui.App) {
		for _, __cv := range __tui_7_views {
			if binder, ok := any(__cv).(tui.AppBinder); ok {
				binder.BindApp(app)
			}
		}
	}

	__unbindApp := func() {
		for _, __cv := range __tui_7_views {
			if unbinder, ok := any(__cv).(tui.AppUnbinder); ok {
				unbinder.UnbindApp()
			}
		}
	}

	view = PaletteView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type PaletteRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *PaletteRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *PaletteRowView) GetRoot() *tui.Element { return v.Root }

func (v *PaletteRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *PaletteRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *PaletteRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *PaletteRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*PaletteRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*PaletteRowView)(nil)

var _ tui.AppUnbinder = (*PaletteRowView)(nil)

var _ tui.PropsUpdater = (*PaletteRowView)(nil)

func PaletteRow(e paletteEntry, selected bool) *PaletteRowView {
	var view PaletteRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	if selected {
		__tui_1 := tui.New(
			tui.WithText("▸"),
			tui.WithTextStyle(cursorStyle()),
		)
		__tui_0.AddChild(__tui_1)
	} else {
		__tui_2 := tui.New(
			tui.WithWidth(1),
		)
		__tui_0.AddChild(__tui_2)
	}
	__tui_3 := tui.New(
		tui.WithText(oneLine(e.Verb, paletteVerbWidth)),
		tui.WithTextStyle(rowStyle(selected, false)),
		tui.WithWidth(paletteVerbWidth),
	)
	__tui_0.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(oneLine(e.Detail, paletteWidth-paletteVerbWidth-6)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_4)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = PaletteRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ProblemBlockView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ProblemBlockView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ProblemBlockView) GetRoot() *tui.Element { return v.Root }

func (v *ProblemBlockView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ProblemBlockView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ProblemBlockView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ProblemBlockView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ProblemBlockView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ProblemBlockView)(nil)

var _ tui.AppUnbinder = (*ProblemBlockView)(nil)

var _ tui.PropsUpdater = (*ProblemBlockView)(nil)

func ProblemBlock(p problem, width int) *ProblemBlockView {
	var view ProblemBlockView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexShrink(0),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	if p.Bad {
		__tui_2 := tui.New(
			tui.WithText("✗ "+p.Name),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_1.AddChild(__tui_2)
	} else {
		__tui_3 := tui.New(
			tui.WithText("! "+p.Name),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_1.AddChild(__tui_3)
	}
	__tui_4 := tui.New(
		tui.WithText(p.State),
		tui.WithTextStyle(toneStyle(problemTone(p))),
	)
	__tui_1.AddChild(__tui_4)
	if p.Where != "" {
		__tui_5 := tui.New(
			tui.WithText(p.Where),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_5)
	}
	__tui_6 := tui.New(
		tui.WithText(fmt.Sprintf("[%d]", p.Goto)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_6)
	__tui_0.AddChild(__tui_1)
	for __idx_0, line := range p.Reason {
		_ = __idx_0
		__tui_7 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		)
		__tui_8 := tui.New(
			tui.WithWidth(2),
		)
		__tui_7.AddChild(__tui_8)
		__tui_9 := tui.New(
			tui.WithText(line),
			tui.WithTextStyle(toneStyle(problemTone(p))),
		)
		__tui_7.AddChild(__tui_9)
		__tui_0.AddChild(__tui_7)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ProblemBlockView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type BoardSectionView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *BoardSectionView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *BoardSectionView) GetRoot() *tui.Element { return v.Root }

func (v *BoardSectionView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *BoardSectionView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *BoardSectionView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *BoardSectionView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*BoardSectionView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*BoardSectionView)(nil)

var _ tui.AppUnbinder = (*BoardSectionView)(nil)

var _ tui.PropsUpdater = (*BoardSectionView)(nil)

func BoardSection(s boardSection, width int, nameWidth int) *BoardSectionView {
	var view BoardSectionView
	var watchers []tui.Watcher

	var __tui_6_views []*BoardLineView
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexShrink(0),
		tui.WithWidth(width),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_2 := tui.New(
		tui.WithText(fmt.Sprint(uint8(s.ID))),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(s.ID.Title()),
		tui.WithTextStyle(sectionTitleStyle()),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithFlexGrow(1),
	)
	__tui_1.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(s.Count),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_5)
	__tui_0.AddChild(__tui_1)
	for __idx_0, l := range s.Body {
		_ = __idx_0
		__tui_6 := BoardLine(l, nameWidth, width)
		__tui_0.AddChild(__tui_6.Root)
		__tui_6_views = append(__tui_6_views, __tui_6)
	}

	for _, __cv := range __tui_6_views {
		watchers = append(watchers, __cv.GetWatchers()...)
	}

	__bindApp := func(app *tui.App) {
		for _, __cv := range __tui_6_views {
			if binder, ok := any(__cv).(tui.AppBinder); ok {
				binder.BindApp(app)
			}
		}
	}

	__unbindApp := func() {
		for _, __cv := range __tui_6_views {
			if unbinder, ok := any(__cv).(tui.AppUnbinder); ok {
				unbinder.UnbindApp()
			}
		}
	}

	view = BoardSectionView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type BoardLineView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *BoardLineView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *BoardLineView) GetRoot() *tui.Element { return v.Root }

func (v *BoardLineView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *BoardLineView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *BoardLineView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *BoardLineView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*BoardLineView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*BoardLineView)(nil)

var _ tui.AppUnbinder = (*BoardLineView)(nil)

var _ tui.PropsUpdater = (*BoardLineView)(nil)

func BoardLine(l boardLine, nameWidth int, width int) *BoardLineView {
	var view BoardLineView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexShrink(0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	if l.Bar != "" {
		__tui_2 := tui.New(
			tui.WithText(l.Bar),
			tui.WithTextStyle(toneStyle(l.Tone)),
		)
		__tui_0.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithWidth(1),
		)
		__tui_0.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText(oneLine(l.Note, width-nameWidth-3)),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_4)
	} else if l.Name != "" {
		__tui_5 := tui.New(
			tui.WithText(oneLine(l.Name, nameWidth)),
			tui.WithWidth(nameWidth),
		)
		__tui_0.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText(oneLine(l.Note, width-nameWidth-3)),
			tui.WithTextStyle(toneStyle(l.Tone)),
		)
		__tui_0.AddChild(__tui_6)
	} else {
		__tui_7 := tui.New(
			tui.WithText(oneLine(l.Note, width-3)),
			tui.WithTextStyle(toneStyle(l.Tone)),
		)
		__tui_0.AddChild(__tui_7)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = BoardLineView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type PageBlockView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *PageBlockView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *PageBlockView) GetRoot() *tui.Element { return v.Root }

func (v *PageBlockView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *PageBlockView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *PageBlockView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *PageBlockView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*PageBlockView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*PageBlockView)(nil)

var _ tui.AppUnbinder = (*PageBlockView)(nil)

var _ tui.PropsUpdater = (*PageBlockView)(nil)

func PageBlock(b pageBlock, width int) *PageBlockView {
	var view PageBlockView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexShrink(0),
	)
	if b.Name != "" {
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(1),
		)
		__tui_2 := tui.New(
			tui.WithText(b.Icon),
			tui.WithTextStyle(toneStyle(b.Tone)),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText(b.Name),
			tui.WithTextStyle(tui.NewStyle().Bold()),
		)
		__tui_1.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithFlexGrow(1),
		)
		__tui_1.AddChild(__tui_4)
		__tui_5 := tui.New(
			tui.WithText(b.State),
			tui.WithTextStyle(toneStyle(b.Tone)),
		)
		__tui_1.AddChild(__tui_5)
		__tui_0.AddChild(__tui_1)
	}
	if b.Meta != "" {
		__tui_6 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		)
		__tui_7 := tui.New(
			tui.WithWidth(2),
		)
		__tui_6.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText(oneLine(b.Meta, width-2)),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_6.AddChild(__tui_8)
		__tui_0.AddChild(__tui_6)
	}
	for __idx_0, line := range b.Body {
		_ = __idx_0
		__tui_9 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		)
		__tui_10 := tui.New(
			tui.WithWidth(2),
		)
		__tui_9.AddChild(__tui_10)
		__tui_11 := tui.New(
			tui.WithText(line),
			tui.WithTextStyle(toneStyle(b.Tone)),
		)
		__tui_9.AddChild(__tui_11)
		__tui_0.AddChild(__tui_9)
	}
	if b.Extra != "" {
		__tui_12 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		)
		__tui_13 := tui.New(
			tui.WithWidth(2),
		)
		__tui_12.AddChild(__tui_13)
		__tui_14 := tui.New(
			tui.WithText(oneLine(b.Extra, width-2)),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_12.AddChild(__tui_14)
		__tui_0.AddChild(__tui_12)
	}
	__tui_15 := tui.New(
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_15)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = PageBlockView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type GridRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *GridRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *GridRowView) GetRoot() *tui.Element { return v.Root }

func (v *GridRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *GridRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *GridRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *GridRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*GridRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*GridRowView)(nil)

var _ tui.AppUnbinder = (*GridRowView)(nil)

var _ tui.PropsUpdater = (*GridRowView)(nil)

func GridRow(cells []gridCell, cellWidth int) *GridRowView {
	var view GridRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexShrink(0),
	)
	for __idx_0, c := range cells {
		_ = __idx_0
		__tui_1 := tui.New(
			tui.WithText(oneLine(c.Left, cellWidth-1)),
			tui.WithWidth(cellWidth),
		)
		__tui_0.AddChild(__tui_1)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = GridRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type LogLineView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *LogLineView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *LogLineView) GetRoot() *tui.Element { return v.Root }

func (v *LogLineView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *LogLineView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *LogLineView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *LogLineView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*LogLineView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*LogLineView)(nil)

var _ tui.AppUnbinder = (*LogLineView)(nil)

var _ tui.PropsUpdater = (*LogLineView)(nil)

func LogLine(l logring.Line) *LogLineView {
	var view LogLineView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_1 := tui.New(
		tui.WithText(l.Time),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(strings.ToUpper(l.Level.String()[:3])),
		tui.WithTextStyle(levelStyle(l.Level)),
	)
	__tui_0.AddChild(__tui_2)
	if l.Component != "" {
		__tui_3 := tui.New(
			tui.WithText("["+l.Component+"]"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_0.AddChild(__tui_3)
	}
	__tui_4 := tui.New(
		tui.WithText(l.Msg),
	)
	__tui_0.AddChild(__tui_4)
	if l.Chat != "" {
		__tui_5 := tui.New(
			tui.WithText("chat="+short(l.Chat)),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_5)
	}
	if l.Attrs != "" {
		__tui_6 := tui.New(
			tui.WithText(l.Attrs),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_6)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = LogLineView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ApprovalView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ApprovalView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ApprovalView) GetRoot() *tui.Element { return v.Root }

func (v *ApprovalView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ApprovalView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ApprovalView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ApprovalView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ApprovalView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ApprovalView)(nil)

var _ tui.AppUnbinder = (*ApprovalView)(nil)

var _ tui.PropsUpdater = (*ApprovalView)(nil)

func Approval(ask *Ask, cursor int) *ApprovalView {
	var view ApprovalView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithPadding(1),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Yellow)),
		tui.WithWidth(paletteWidth),
	)
	if ask != nil {
		__tui_1 := tui.New(
			tui.WithText("approve "+ask.Action.Kind),
			tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Yellow)),
		)
		__tui_0.AddChild(__tui_1)
		if ask.Action.Target != "" {
			__tui_2 := tui.New(
				tui.WithText("→ "+ask.Action.Target),
				tui.WithTextStyle(tui.NewStyle().Bold()),
			)
			__tui_0.AddChild(__tui_2)
		}
		__tui_3 := tui.New(
			tui.WithHR(),
		)
		__tui_0.AddChild(__tui_3)
		for i, o := range ask.Options {
			_ = i
			__tui_4 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				tui.WithGap(1),
			)
			if i == cursor {
				__tui_5 := tui.New(
					tui.WithText("▸"),
					tui.WithTextStyle(cursorStyle()),
				)
				__tui_4.AddChild(__tui_5)
			} else {
				__tui_6 := tui.New(
					tui.WithWidth(1),
				)
				__tui_4.AddChild(__tui_6)
			}
			__tui_7 := tui.New(
				tui.WithText(fmt.Sprintf("%d", i+1)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
			)
			__tui_4.AddChild(__tui_7)
			__tui_8 := tui.New(
				tui.WithText(o.Label),
				tui.WithTextStyle(rowStyle(i == cursor, false)),
			)
			__tui_4.AddChild(__tui_8)
			if o.Widens {
				__tui_9 := tui.New(
					tui.WithText("(wider than asked)"),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
				)
				__tui_4.AddChild(__tui_9)
			}
			__tui_0.AddChild(__tui_4)
		}
		__tui_10 := tui.New(
			tui.WithText("↑↓ pick · Enter allow · n or Esc denies"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_10)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ApprovalView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ToolDetailView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ToolDetailView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ToolDetailView) GetRoot() *tui.Element { return v.Root }

func (v *ToolDetailView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ToolDetailView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ToolDetailView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ToolDetailView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ToolDetailView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ToolDetailView)(nil)

var _ tui.AppUnbinder = (*ToolDetailView)(nil)

var _ tui.PropsUpdater = (*ToolDetailView)(nil)

func ToolDetail(t transcript.Tool) *ToolDetailView {
	var view ToolDetailView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexShrink(0),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	if t.Err != "" {
		__tui_2 := tui.New(
			tui.WithText("✗ failed"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		__tui_1.AddChild(__tui_2)
	} else if t.Running {
		__tui_3 := tui.New(
			tui.WithText("◐ running"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow)),
		)
		__tui_1.AddChild(__tui_3)
	} else {
		__tui_4 := tui.New(
			tui.WithText("⏺ done"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
		)
		__tui_1.AddChild(__tui_4)
	}
	__tui_5 := tui.New(
		tui.WithText(toolTiming(t, t.Started)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_1.AddChild(__tui_5)
	__tui_0.AddChild(__tui_1)
	__tui_6 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText("input"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_7)
	if t.Args == "" {
		__tui_8 := tui.New(
			tui.WithText("none"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_8)
	} else {
		__tui_9 := tui.New(
			tui.WithText(t.Args),
		)
		__tui_0.AddChild(__tui_9)
	}
	__tui_10 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithText("output"),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_11)
	if t.Err != "" {
		__tui_12 := tui.New(
			tui.WithText(t.Err),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		__tui_0.AddChild(__tui_12)
	} else if t.Running {
		if t.Stream != "" {
			__tui_13 := tui.New(
				tui.WithText(t.Stream),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_0.AddChild(__tui_13)
		} else {
			__tui_14 := tui.New(
				tui.WithText("still running"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_0.AddChild(__tui_14)
		}
	} else if t.Result == "" {
		__tui_15 := tui.New(
			tui.WithText("none"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_15)
	} else {
		__tui_16 := tui.New(
			tui.WithText(t.Result),
		)
		__tui_0.AddChild(__tui_16)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ToolDetailView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
