// Code generated by tui generate. DO NOT EDIT.
// Source: pane.gsx

package tui

import (
	"math"

	tui "github.com/grindlemire/go-tui"
)

type scrollPane struct {
	// box is the scrollable element. The owner passes it in so it can move the keyboard here;
	// the pane needs it for the scroll geometry.
	box *tui.Ref
	// offset is where the reader scrolled to, and sticky says they have not scrolled away yet.
	// Both are the pane's own business — scrolling the log must not unstick the transcript.
	offset *tui.State[int]
	sticky *tui.State[bool]

	// focus is the root's focusOn. A click has to move the keyboard the same way Tab does, and
	// Element.Focus would only set the element's own flag without telling the focus manager.
	focus func(*tui.Ref)

	title string
	// focused is whether this pane holds the keyboard, passed in rather than read off the element:
	// the border is chosen BEFORE the element exists, and the element's own flag is one frame stale.
	focused  bool
	height   int // rows; 0 means take whatever is left
	children []*tui.Element
}

type Pane struct {
	// Box is the caller's handle on the element, so it can move the keyboard here.
	Box   *tui.Ref
	Focus func(*tui.Ref)
	Title string
	// Height in rows; zero grows to fill what is left.
	Height int
	// Follow starts the pane pinned to its tail. A transcript and a log grow at the bottom and that
	// is where the new material is; a PAGE has its beginning at the top, and opening it already
	// scrolled past everything shows an empty box.
	Follow bool
	// Focused is whether this pane holds the keyboard, passed in rather than read off the element:
	// the border is chosen BEFORE the element exists, and the element's own flag is one frame stale.
	Focused bool
	// Offset lets the OWNER hold the scroll position instead of the pane. Only the overlays use it,
	// and for one reason: an overlay's wheel has to be handled by the root, because the framework
	// walks mouse listeners in tree order and the transcript pane comes before anything inside a
	// modal — so a notch over the workspace view would scroll the conversation behind it. Left nil
	// the position stays here, which is what every pane in the main layout wants.
	Offset *tui.State[int]
}

func ScrollPane(p Pane, children []*tui.Element) *scrollPane {
	if p.Offset == nil {
		p.Offset = tui.NewState(0)
	}
	return &scrollPane{
		box:      p.Box,
		offset:   p.Offset,
		sticky:   tui.NewState(p.Follow),
		focus:    p.Focus,
		title:    p.Title,
		focused:  p.Focused,
		height:   p.Height,
		children: children,
	}
}

func (p *scrollPane) HandleMouse(me tui.MouseEvent) bool {
	el := p.box.El()
	if el == nil || !el.ContainsPoint(me.X, me.Y) {
		return false
	}
	switch me.Button {
	case tui.MouseWheelUp:
		p.scrollBy(-wheelStep)
		return true
	case tui.MouseWheelDown:
		p.scrollBy(wheelStep)
		return true
	case tui.MouseLeft:
		// The bar is grabbable. A drag is checked alongside a press because they are the same
		// gesture continued — the framework reports motion only while a button is held, which is
		// exactly a drag and is the only motion it reports at all.
		if (me.Action == tui.MousePress || me.Action == tui.MouseDrag) && onScrollbar(el, me.X) {
			scrollToPoint(el, p.offset, p.sticky, me.Y)
			return true
		}
		if me.Action == tui.MousePress && p.focus != nil {
			p.focus(p.box)
			return true
		}
	}
	return false
}

func (p *scrollPane) IsFocused() bool {
	el := p.box.El()
	return el != nil && el.IsFocused()
}

func (p *scrollPane) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnFocused(tui.Rune('j'), func(tui.KeyEvent) { p.scrollBy(1) }),
		tui.OnFocused(tui.Rune('k'), func(tui.KeyEvent) { p.scrollBy(-1) }),
		tui.OnFocused(tui.KeyDown, func(tui.KeyEvent) { p.scrollBy(1) }),
		tui.OnFocused(tui.KeyUp, func(tui.KeyEvent) { p.scrollBy(-1) }),
		tui.OnFocused(tui.KeyPageDown, func(tui.KeyEvent) { p.scrollBy(10) }),
		tui.OnFocused(tui.KeyPageUp, func(tui.KeyEvent) { p.scrollBy(-10) }),
		tui.OnFocused(tui.Rune('g'), func(tui.KeyEvent) { p.scrollTop() }),
		tui.OnFocused(tui.KeyHome, func(tui.KeyEvent) { p.scrollTop() }),
		tui.OnFocused(tui.Rune('G'), func(tui.KeyEvent) { p.scrollEnd() }),
		tui.OnFocused(tui.KeyEnd, func(tui.KeyEvent) { p.scrollEnd() }),
	}
}

func (p *scrollPane) scrollOffset() int {
	if p.sticky.Get() {
		return math.MaxInt
	}
	return p.offset.Get()
}

func (p *scrollPane) scrollBy(d int) {
	el := p.box.El()
	if el == nil {
		return
	}
	_, at := el.ScrollOffset()
	_, maxY := el.MaxScroll()
	y := min(max(at+d, 0), maxY)
	p.offset.Set(y)
	p.sticky.Set(y >= maxY)
}

func onScrollbar(el *tui.Element, x int) bool {
	r := el.ContentRect()
	return x == r.Right()-1
}

func scrollToPoint(el *tui.Element, offset *tui.State[int], sticky *tui.State[bool], y int) {
	_, maxY := el.MaxScroll()
	track := el.ContentRect()
	if maxY <= 0 || track.Height <= 1 {
		return // nothing to scroll, or no track to aim at
	}
	at := min(max(y-track.Y, 0), track.Height-1) * maxY / (track.Height - 1)
	offset.Set(at)
	if sticky != nil {
		sticky.Set(at >= maxY)
	}
}

func (p *scrollPane) scrollTop() {
	p.sticky.Set(false)
	p.offset.Set(0)
}

func (p *scrollPane) scrollEnd() { p.sticky.Set(true) }

func (p *scrollPane) Render(app *tui.App) *tui.Element {
	var __tui_0 *tui.Element
	if p.height > 0 {
		__tui_1 := tui.New(
			tui.WithFocusable(true),
			tui.WithScrollable(tui.ScrollVertical),
			tui.WithScrollOffset(0, p.scrollOffset()),
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithFlexShrink(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithHeight(p.height),
			tui.WithBorderTitle(p.title),
			tui.WithBorder(paneBorder(p.focused)),
			tui.WithBorderStyle(paneBorderStyle(p.focused)),
		)
		p.box.Set(__tui_1)
		for _, __child := range p.children {
			__tui_1.AddChild(__child)
		}
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else {
		__tui_2 := tui.New(
			tui.WithFocusable(true),
			tui.WithScrollable(tui.ScrollVertical),
			tui.WithScrollOffset(0, p.scrollOffset()),
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithFlexGrow(1),
			tui.WithMinHeight(0),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithBorderTitle(p.title),
			tui.WithBorder(paneBorder(p.focused)),
			tui.WithBorderStyle(paneBorderStyle(p.focused)),
		)
		p.box.Set(__tui_2)
		for _, __child := range p.children {
			__tui_2.AddChild(__child)
		}
		if __tui_0 == nil {
			__tui_0 = __tui_2
		}
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (p *scrollPane) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*scrollPane)
	if !ok {
		return
	}
	p.title = f.title
	p.focused = f.focused
	p.height = f.height
	p.children = f.children
}

func (p *scrollPane) UpdateProps(fresh tui.Component) {
	p.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*scrollPane)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (p *scrollPane) bindAppFields(app *tui.App) {
	if p.offset != nil {
		p.offset.BindApp(app)
	}
	if p.sticky != nil {
		p.sticky.BindApp(app)
	}
}

func (p *scrollPane) BindApp(app *tui.App) {
	p.bindAppFields(app)
}

var _ tui.AppBinder = (*scrollPane)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener   = (*scrollPane)(nil)
	_ tui.MouseListener = (*scrollPane)(nil)
)
