// Code generated by tui generate. DO NOT EDIT.
// Source: sidebar.gsx

package tui

import (
	tui "github.com/grindlemire/go-tui"
)

type sidebar struct {
	box    *tui.Ref
	offset *tui.State[int]

	cursor   *tui.State[int]
	activeID *tui.State[string]
	filter   *tui.State[listFilter]
	// focused is whether this pane holds the keyboard, passed in rather than read off the element,
	// because the title has to be built before the element it titles exists.
	focused bool
	// rows, onSelect and focus are the root's methods. They are function fields, which UpdateProps
	// deliberately does not copy — that is fine here, because they are method values on the one
	// root that outlives every render.
	rows     func() []row
	sizes    func() (chats, runs int)
	onSelect func(row)
	focus    func(*tui.Ref)
}

type List struct {
	// Box is the caller's handle on the element, so it can move the keyboard here when a command
	// asks for the list.
	Box      *tui.Ref
	Focus    func(*tui.Ref)
	Cursor   *tui.State[int]
	ActiveID *tui.State[string]
	Filter   *tui.State[listFilter]
	// Rows, Sizes and OnSelect are the root's methods. Function fields, which UpdateProps
	// deliberately does not copy — fine here, because they are method values on the one root that
	// outlives every render.
	Rows     func() []row
	Sizes    func() (chats, runs int)
	OnSelect func(row)
	Focused  bool
}

type chip struct {
	Filter listFilter
	Label  string
	Width  int
}

const (
	rowLines = 2
	// chipLines is the clickable part of the header.
	chipLines = 1
	// headerLines is all of it, spacer included: what row 0 begins after.
	headerLines = chipLines + 1
)

func Sidebar(l List) *sidebar {
	return &sidebar{
		box:      l.Box,
		offset:   tui.NewState(0),
		cursor:   l.Cursor,
		activeID: l.ActiveID,
		filter:   l.Filter,
		focused:  l.Focused,
		rows:     l.Rows,
		sizes:    l.Sizes,
		onSelect: l.OnSelect,
		focus:    l.Focus,
	}
}

func (s *sidebar) chatCount() int { c, _ := s.sizes(); return c }

func (s *sidebar) runCount() int { _, r := s.sizes(); return r }

func (s *sidebar) setFilter(f listFilter) {
	if s.filter.Get() == f {
		return
	}
	s.filter.Set(f)
	s.cursor.Set(-1)
	s.offset.Set(0)
	s.move(1)
}

func (s *sidebar) cycleFilter(d int) {
	s.setFilter(listFilter((int(s.filter.Get()) + d + filterCount) % filterCount))
}

func chips(chats, runs int) []chip {
	return []chip{
		{filterChats, chipLabel("chats", chats, chipWidth), chipWidth},
		{filterRuns, chipLabel("agents", runs, lastChipWidth), lastChipWidth},
	}
}

func (s *sidebar) HandleMouse(me tui.MouseEvent) bool {
	el := s.box.El()
	if el == nil || !el.ContainsPoint(me.X, me.Y) {
		return false
	}
	switch me.Button {
	case tui.MouseWheelUp:
		s.scrollBy(-wheelStep)
		return true
	case tui.MouseWheelDown:
		s.scrollBy(wheelStep)
		return true
	case tui.MouseLeft:
		// The bar first, and drags with it: grabbing it must not also pick whatever row the pointer
		// happens to be beside.
		if (me.Action == tui.MousePress || me.Action == tui.MouseDrag) && onScrollbar(el, me.X) {
			// No sticky flag: the list is a fixed set of rows and does not follow a tail, so where
			// the reader puts it is where it stays.
			scrollToPoint(el, s.offset, nil, me.Y)
			return true
		}
		if me.Action != tui.MousePress {
			return false
		}
		if s.focus != nil {
			s.focus(s.box)
		}
		s.clickAt(me.X, me.Y)
		return true
	}
	return false
}

func (s *sidebar) clickAt(x, y int) {
	el := s.box.El()
	if el == nil {
		return
	}
	content := el.ContentRect()
	_, at := el.ScrollOffset()
	line := y - content.Y + at
	if line < 0 {
		return
	}
	if line < chipLines {
		s.clickFilter(x - content.X)
		return
	}
	if line < headerLines {
		return // the blank under the chips: not a chip, and not a row either
	}
	s.clickRow((line - headerLines) / rowLines)
}

func (s *sidebar) clickFilter(dx int) {
	left := 0
	for _, c := range chips(s.chatCount(), s.runCount()) {
		if dx >= left && dx < left+c.Width {
			s.setFilter(c.Filter)
			return
		}
		left += c.Width
	}
}

func (s *sidebar) clickRow(i int) {
	rows := s.rows()
	if i < 0 || i >= len(rows) || !rows[i].Selectable() {
		return // a placeholder, or the padding below the last row
	}
	s.cursor.Set(i)
	s.onSelect(rows[i])
}

func (s *sidebar) scrollBy(d int) {
	el := s.box.El()
	if el == nil {
		return
	}
	_, at := el.ScrollOffset()
	_, maxY := el.MaxScroll()
	s.offset.Set(min(max(at+d, 0), maxY))
}

func (s *sidebar) IsFocused() bool {
	el := s.box.El()
	return el != nil && el.IsFocused()
}

func (s *sidebar) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnFocused(tui.Rune('j'), func(tui.KeyEvent) { s.move(1) }),
		tui.OnFocused(tui.Rune('k'), func(tui.KeyEvent) { s.move(-1) }),
		tui.OnFocused(tui.KeyDown, func(tui.KeyEvent) { s.move(1) }),
		tui.OnFocused(tui.KeyUp, func(tui.KeyEvent) { s.move(-1) }),
		tui.OnFocused(tui.KeyEnter, func(tui.KeyEvent) { s.selectRow() }),
		tui.OnFocused(tui.KeyLeft, func(tui.KeyEvent) { s.cycleFilter(-1) }),
		tui.OnFocused(tui.KeyRight, func(tui.KeyEvent) { s.cycleFilter(1) }),
	}
}

func (s *sidebar) move(d int) {
	rows := s.rows()
	i := s.cursor.Get()
	for range len(rows) {
		i += d
		if i < 0 || i >= len(rows) {
			return
		}
		if rows[i].Selectable() {
			s.cursor.Set(i)
			s.reveal()
			return
		}
	}
}

func (s *sidebar) reveal() {
	el := s.box.El()
	if el == nil {
		return
	}
	visible := el.ContentRect().Height
	if visible <= 0 {
		return
	}
	_, maxY := el.MaxScroll()
	top := s.offset.Get()
	at := headerLines + s.cursor.Get()*rowLines
	switch {
	case at < top:
		top = at
	case at+rowLines > top+visible:
		top = at + rowLines - visible
	}
	s.offset.Set(min(max(top, 0), maxY))
}

func (s *sidebar) selectRow() {
	rows := s.rows()
	i := s.cursor.Get()
	if i < 0 || i >= len(rows) {
		return
	}
	s.onSelect(rows[i])
}

func (s *sidebar) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithFocusable(true),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, s.offset.Get()),
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithWidth(sidebarWidth),
		tui.WithBorderTitle(paneTitle(" conversations ", s.focused)),
		tui.WithBorder(paneBorder(s.focused)),
		tui.WithBorderStyle(paneBorderStyle(s.focused)),
	)
	s.box.Set(__tui_0)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexShrink(0),
	)
	for __idx_0, c := range chips(s.chatCount(), s.runCount()) {
		_ = __idx_0
		__tui_2 := tui.New(
			tui.WithText(c.Label),
			tui.WithWidth(c.Width),
			tui.WithTextStyle(chipStyle(s.filter.Get() == c.Filter)),
		)
		__tui_1.AddChild(__tui_2)
	}
	__tui_0.AddChild(__tui_1)
	__tui_3 := tui.New(
		tui.WithHeight(1),
		tui.WithFlexShrink(0),
	)
	__tui_0.AddChild(__tui_3)
	for i, r := range s.rows() {
		_ = i
		__tui_4 := app.Mount(s, tui.MountKey(0, i), func() tui.Component {
			return SidebarRow(r, i == s.cursor.Get(), r.ID != "" && r.ID == s.activeID.Get())
		})
		__tui_0.AddChild(__tui_4)
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (s *sidebar) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*sidebar)
	if !ok {
		return
	}
	s.focused = f.focused
}

func (s *sidebar) UpdateProps(fresh tui.Component) {
	s.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*sidebar)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (s *sidebar) bindAppFields(app *tui.App) {
	if s.offset != nil {
		s.offset.BindApp(app)
	}
	if s.cursor != nil {
		s.cursor.BindApp(app)
	}
	if s.activeID != nil {
		s.activeID.BindApp(app)
	}
	if s.filter != nil {
		s.filter.BindApp(app)
	}
}

func (s *sidebar) BindApp(app *tui.App) {
	s.bindAppFields(app)
}

var _ tui.AppBinder = (*sidebar)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener   = (*sidebar)(nil)
	_ tui.MouseListener = (*sidebar)(nil)
)
